### ISSUE TITLE
Request for extension: VNC Proxy

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/nbserverproxy#24]
Now that nbserverproxy has websocket support, it'll be great to write an extension that utilizes https://github.com/novnc/noVNC (VNC in browser via websockets) to provide VNC inside JupyterHub. It should just require access to a X socket, which in JupyterHub deployments can be provided via Docker.

**Comment by ryanlovett** [comment]
nbserverproxy can easily serve up the noVNC client, but it is more challenging (for me at least) to get noVNC to connect to a VNC server running in the notebook server. noVNC isn't a server-side VNC client. (though I don't know enough about node to know whether noVNC can run server-side)

Another possibility besides noVNC is GTK+ broadway where gvncviewer acts as the server-side VNC client and exports its display via broadway. nbserverproxy doesn't support websocket subprotocol sufficiently for this to work since broadway uses that feature. Or at least, I've run into a problem when specifying the subprotocol type.

Also, @minrk's list post:
https://groups.google.com/forum/#!searchin/jupyter/vnc$20javascript%7Csort:date/jupyter/iQCJkHIw7wo/jNcW5GoYAwAJ

**Comment by ryanlovett** [comment]
Scratching what I wrote in the first paragraph. novnc let's you specify the full path to the websocket.

PR #26 will enable both novnc and broadway to work.

**Comment by ryanlovett** [comment]
Hi @mbmilligan,

Check out https://github.com/ryanlovett/nbnovnc/. Also try its binder. Still early but let me know what you think.

**Comment by mbmilligan** [comment]
Nifty - works as a proof of concept, but rather prone to server disconnects. Happy to contribute to getting this working though -- I'll follow up in the linked repo. Thanks!

**Comment by ryanlovett** [comment]
Thanks @mbmilligan ! I recall viewing video of a talk you gave on how Jupyter fits into your institution's scientific workflow. I vigorously nodded at my desk (to an audience of zero) when you mentioned VNC+Jupyter because I had been thinking the same thing!

**Comment by ryanlovett** [comment]
Closing since I think https://github.com/ryanlovett/nbnovnc/ is a good enough example / starting point for this.
